### ISSUE TITLE
Plot a correlation heatmap

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#1]
**Plot a correlation heatmap**
Fork the dataset and the Python notebook

Locate **#Issue 1** in the Jupyter notebook
Using ALL columns in the data set, plot a correlation heatmap.
Print the names of the 4 features that have the highest correlation with Quality

Your PR must contain the edited ipynb file with the same name as the original. Kindly edit only the block of code pertaining to the issue :)

**Comment by abhishek-mishra17** [comment]
hey @pk-95  i would like to work on this

**Comment by Devprakash613** [comment]
I would like to work on this

**Comment by DevprakashBisoi** [comment]
I would like to work on this
