### ISSUE TITLE
Visualize Boxplots

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#2]
**Draw boxplots**
Fork the dataset and the Python notebook

Locate **#Issue 2** in the Jupyter notebook
A boxplot has been given by the developer only for citric acid and density. Plot similar boxplots for each of the columns against quality (using the feature 'quality' as one of the axes). Mention any linear trends and also use a color palette to make it look appealing.

Your PR must contain the edited ipynb file with the same name as the original. Kindly edit only the block of code pertaining to the issue :)

**Comment by DevprakashBisoi** [comment]
I will be working on this

**Comment by abhishek-mishra17** [comment]
hey @pk-95  i would like to work on this
