### ISSUE TITLE
Enhancement for issue #7

### ISSUE THREAD

**Issue by abhishek-mishra17** [acmpesuecc/Wine_Quality_Prediction#23]
for the issue #7  try to increase the accuracy of random forest classifier model by including more features , etc.

**Comment by pk-95** [comment]
Hey @abhishek-pes for this particular issue I guess if you could create a random forest classifier using different features but without classifying as good/bad (i.e, predicting quality as 3,4,5,6,7,8 itself) let me know :))

**Comment by abhishek-mishra17** [comment]
@pk-95  yeah I have done it .. shall I just put a PR then?
