### ISSUE TITLE
Plotting Scatter-plots

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#3]
**Scatter Plots**
Fork  and clone the dataset and the Python notebook

Locate **#Issue 3** in the Jupyter notebook
Scatter plots need to be plotted amongst each of the feature columns ( taking all possible combinations of 2) and must be given the 'hue' of the target columns, 'quality'. Mention trends, if any, using print statements. 

Your PR must contain the edited ipynb file with the same name as the original. Kindly edit only the block of code pertaining to the issue :)

**Comment by svscsantosh** [comment]
Hi,
I would like to work on this

**Comment by abhishek-mishra17** [comment]
hi @pk-95  I would like to work on this
