### ISSUE TITLE
Scaling the features

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#4]
**Scaling the features columns**
Fork and clone the dataset and the Python notebook

Locate **#Issue 4** in the Jupyter notebook
Import and define a scaler for the feature columns. Take into consideration the distribution of the data and select an appropriate one.

Your PR must contain the edited ipynb file with the same name as the original. Kindly edit only the block of code pertaining to the issue :)

**Comment by abhishek-mishra17** [comment]
hi @pk-95  I would like to work on this
