### ISSUE TITLE
Creating a KNN Classifier Model

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#5]
**Create a KNN Classifier Model with default parameters**
Fork the dataset and the Python notebook

Locate **#Issue 5** in the Jupyter notebook
Create a K Nearest Neighbours Classifier Model with default parameters. (Model does not have to be created from scratch, sci-kit learn defined models are accepted)
Use the variable 'model1' to instantiate this model, and fit it on the training data.

Your PR must contain the edited ipynb file with the same name as the original. Kindly edit only the block of code pertaining to the issue :)

**Comment by abhishek-mishra17** [comment]
hi @pk-95 I would like to work on this

**Comment by DevprakashBisoi** [comment]
I would like to work on this
