### ISSUE TITLE
Improving the KNN model

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#6]
**Improving the KNN model from issue #5 for better accuracy**
Fork the dataset and the Python notebook

Locate **#Issue 6** in the Jupyter notebook
In a new cell, define a new K nearest neighbours classifier and work with the parameters of the model in order to improve accuracy. (Model doesn't have to be defined from scratch, sci-kit learn defined models are accepted). 
Train it on the training data and predict on the test data.
The minimum test accuracy required for an accepted PR is 74%, but if you can do better, brownie points await you ;)
(Note: Don't perform scaling/train test split again, work only with tuning the model parameters)

Your PR must contain the edited ipynb file with the same name as the original. 
You must also briefly explain in your words what parameters you changed and their effect (in short). This can be inserted within the file using markdown or docstring.

Kindly edit only the block of code pertaining to the issue :)

**Comment by abhishek-mishra17** [comment]
hi @pk-95 I would like to work on this

**Comment by DevprakashBisoi** [comment]
I would like to work on this
