### ISSUE TITLE
Random Forest Classifier

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#7]
**Creating a Random Forest Classifier**
Fork the dataset and the Python notebook

Locate **#Issue 7** in the Jupyter notebook (or just add it in the end after the solution to issue #6 )
This issue requires you to make 2 Random Forest Classifier models
RF1:
In a new cell, define a new Random Forest Classifier. Use default parameters (Model does not have to be created from scratch, sci-kit learn defined models are accepted).
Use the variable 'rf1' to instantiate this model, and fit it on the training data. Make predictions on the test data.

RF2:
In a new cell, define another Random Forest Classifier. In this one, you are expected to fine tune the parameters of the model and obtain the best accuracy you can achieve. The bounty for this issue is variable and will be given on the performance of this second RF model. Naturally, we expect it to perform better than the KNN model (Model doesn't have to be defined from scratch, sci-kit learn defined models are accepted). 
Train it on the training data and predict on the test data.

(Note: Don't perform scaling/train test split again, work only with tuning the model parameters)

Your PR must contain the edited ipynb file with the same name as the original. 
You must also briefly explain in your words what parameters you changed and their effect (in short). This can be inserted within the file using markdown or docstring.

Kindly edit only the block of code pertaining to the issue :)

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Please assign this issue to me, would like to contribute to it

**Comment by SriniRaghav007** [comment]
assign this issue to me

**Comment by abhishek-mishra17** [comment]
hey @pk-95  I would like to work on this

**Comment by DevprakashBisoi** [comment]
I would like to work on this
