### ISSUE TITLE
Better models?

### ISSUE THREAD

**Issue by pk-95** [acmpesuecc/Wine_Quality_Prediction#8]
**Using different approaches to get better results**
So far we've considered KNN classifiers and Random Forest Classifiers. It is most likely that a well designed Random Forest would have given the better result of the two. What we're wondering is, do you think there's any better way to solve this problem?
Do you know any other algorithms you'd like to use? A neural network perhaps? Or maybe you'd like to go with a more complex approach and use an ensemble? The choice is yours, blow us away with a well constructed model which gives comparable, if not better results than the initial ones used.

Code in a NEW Jupyter notebook (ipynb) from the beginning and select the feature columns you deem appropriate(with an explanation). You can choose to leave out the visualization part, or can use your own visualizations to draw insights, and can scale the data as you please. We just want you to either come up with an improvement with a better model or use a more complex approach like neural nets to see whether they give us better results. 

Your PR must contain a new ipynb file with comments/explanations where required.

 This is an open ended question with no fixed bounty. You will be awarded based on your final accuracy/innovative approach and other such factors (based on overall quality of notebook as well)

**Comment by abhishek-mishra17** [comment]
hey @pk-95 I would like to work on this

**Comment by RakshithRAcharya** [comment]
Hey!...can I work on this??

**Comment by DevprakashBisoi** [comment]
I would like to work on this

**Comment by pk-95** [comment]
!bounty 0
